steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    gcloud container clusters list --format="value[separator=':'](name)" | cat > /workspace/CLOUDSDK_CONTAINER_CLUSTER.txt
    cat CLOUDSDK_CONTAINER_CLUSTER.txt
    cat CLOUDSDK_CONTAINER_CLUSTER.txt | xargs -L 1 tee ${_CLOUDSDK_CONTAINER_CLUSTER}
    echo '1'
- name: "gcr.io/cloud-builders/docker"
  waitFor: ['-']
  args: ["build", "-t", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./flask.yaml
  - --image=europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest
  - --location=${_LOCATION}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  env:
  - '${_LOCATION}=europe-west2'
images:
- "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"
