steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    $(gcloud container clusters list --format="value[separator=':'](name)")=${_CLOUDSDK_CONTAINER_CLUSTER}
    echo '1'
    if (( -z ${_CLOUDSDK_CONTAINER_CLUSTER} )); then
       exit 1
       echo "Cluster not found!"
    else
       echo ${_CLOUDSDK_CONTAINER_CLUSTER};
       echo ${_CLOUDSDK_CONTAINER_CLUSTER} > /workspace/${_CLOUDSDK_CONTAINER_CLUSTER}.txt;
       exit 0
    fi
- name: "gcr.io/cloud-builders/docker"
  waitFor: ['-']
  args: ["build", "-t", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./flask.yaml
  - --image=europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest
  - --location=europe-west2
  - --cluster=studyjam-cluster-prod
  env:
  - '${_LOCATION}=europe-west2'
  - '${_CLOUDSDK_CONTAINER_CLUSTER}=$(cat /workspace/${_CLOUDSDK_CONTAINER_CLUSTER}.txt)'
images:
- "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"
