steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"]
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    if [[ -z gcloud container clusters ]]; then
       exit 1
       echo "Cluster not found!"
    else
       _CLOUDSDK_CONTAINER_CLUSTER=$(gcloud container clusters list --format="value[separator=':'](name))"
    fi
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./flask.yaml
  - --image=europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest
  - --location=europe-west2
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
images:
- "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"
